### ISSUE TITLE
Feature Request: Pull Feats, Traits, Items, and Class abilities from PF1e Content and PF1e Archetypes and Class abilities

### ISSUE THREAD

**Issue by baileymh** [Lavaeolous/PF1-StatBlock-Converter-Module#360]
Hey, 
Great work with this module! Please keep up the hard work, it's really appreciated. 

I'm one of the mod authors for the PF1e Content and PF1e Archetypes, I was wondering if it would be possible for your module to attempt to pull and use the items from ours? Obviously naming differs for some statblocks, so it might not be perfect, but PF1e Content has most of the named magic items, wondrous items, all feats and traits, and the Archetypes module has the vast majority of class abilities and archetype features.

**Comment by Lavaeolous** [comment]
Sure, thats possible right now via the custom compendiums one can enter in the sbc settings (pack names can be found via "game.packs").
SBC prioritizes custom compendia when searching for entities and stops when the first match is found. This could be problematic, as there seem to be some duplicates with differing content, at least from the first glance i took.

For example "Aboleth" is included twice in the class abilities, once as an oracle curse and once as an hunter animal focus. SBC has no way to know which one would be the correct one.

I'll test this when i find the time.

**Comment by baileymh** [comment]
For some reason I am unable to get sbc to use the custom compendiums.
I have them entered according to the game.packs, but it isn't finding the items in them. 

It was unable to find feats, and items. 
With debugging on, I see that Items are being created with id undefined, not sure if that is related.
![image](https://user-images.githubusercontent.com/48079051/109102753-85e04800-76f7-11eb-92bc-724f526d564b.png)
![image](https://user-images.githubusercontent.com/48079051/109102696-69dca680-76f7-11eb-9e13-1cdc21e19be2.png)

**Comment by Hanhula** [comment]
I'm also having issues getting SBC to recognise those compendia, and compendia of my own. I just tried to import an Evangelist to take advantage of the new prestige class update, and yet SBC is still both creating its own feats and classes despite having correctly configured the compendia to be used:
```world.hans-magic-items, world.hans-class-abilities, world.hans-classes, world.hans-mythic-abilities, world.hans-feats, world.hans-common-buffs, world.hans-traits, world.hans-spells,  pf-content.feats,  pf-content.traits,  pf-content.artifacts, pf-content.magicitems, pf-content.wondrous, pf-content.pf-35-content, pf-content.pf-items, pf1e-archetypes.pf-archetypes, pf1e-archetypes.pf-class-abilities, pf1e-archetypes.pf-arch-features, pf1e-archetypes.pf-prestige-classes, pf1e-archetypes.pf-prestige-features```
That's what I have in my SBC compendia-adding section, and it confirms they're all correct with no typos. 

For an example statblock, try adding the compendia to SBC and then try importing this:

```Lady Ceridwen Undria
Female rakshasa-spawn tiefling evangelist 10/magus (eldritch archer, fiend flayer, hexcrafter) 4/wizard (spellslinger) 1
N Medium outsider (native)
Init +13; Senses darkvision 60 ft.; Perception +20
Defense
AC 32, touch 18, flat-footed 24 (+14 armor, +6 Dex, +2 dodge)
hp 167 (15 HD; 1d6+14d8+49)
Fort +15, Ref +21, Will +16
Resist cold 5, electricity 5, fire 5
Offense
Speed 30 ft. (20 ft. in armor)
Ranged +5 enhanced revolver +21/+21/+16 (3d4+16 force/×4)
Special Attacks arcane pool (+4, 14 points), hex arcana (distant spellstrike, reach spellstrike, slumber, spell blending [2 spells of lower level]), improved spell combat, spellstrike
Spell-Like Abilities (CL 15th; concentration +18)
   3/day—modify memory (DC 19)
   2/day—locate object
   1/day—imprisonment (DC 22)
Magus (Eldritch Archer, Fiend Flayer, Hexcrafter) Spells Prepared (CL 15th; concentration +23)
   5th—cosmic ray (DC 23), teleport
   4th—arcana theft, black tentacles, dimension door (3)
   3rd—battering blast (DC 21), displacement, fireball (DC 21), gloomblind bolts (DC 21), haste, lightning bolt (DC 21)
   2nd—acid arrow, glitterdust (DC 20), invisibility, kalistocrat's nightmare (DC 20), light prison (DC 20), mirror image, scorching ray
   1st—chill touch (2, DC 19), frostbite (2), grease, shocking grasp (2)
   0 (at will)—arcane mark, detect magic, mage hand, open/close (DC 18), prestidigitation
Wizard (Spellslinger) Spells Prepared (CL 1st; concentration +9)
   1st—invisibility alarm, true strike
   Opposition Schools Divination, Enchantment, Illusion, Necromancy
Statistics
Str 11, Dex 30, Con 16, Int 26, Wis 14, Cha 16
Base Atk +10; CMB +10; CMD 32
Feats Arcane Strike, Deadly Aim, Deific Obedience, Dimensional Agility, Dimensional Assault, Dimensional Dervish, Gunsmithing, Point-Blank Shot, Precise Shot, Rapid Shot, Spell Cartridges
Traits Magical Knack, Reactionary
Skills Acrobatics +13 (+9 to jump), Appraise +16, Bluff +21, Climb +2, Diplomacy +21, Disguise +8, Escape Artist +13, Fly +12, Heal +10, Intimidate +16, Knowledge (arcana) +16, Knowledge (dungeoneering) +13, Knowledge (engineering) +13, Knowledge (geography) +16, Knowledge (history) +21, Knowledge (local) +21, Knowledge (nature) +16, Knowledge (nobility) +26, Knowledge (planes) +26, Knowledge (religion) +14, Linguistics +21, Perception +20, Ride +12, Sense Motive +22, Spellcraft +26, Stealth +12, Survival +6, Swim +2; Racial Modifiers +2 Disguise, +2 Sense Motive
Languages Abyssal, Aquan, Auran, Celestial, Common, Daemonic, Draconic, Dwarven, Elven, Gnome, Goblin, Halfling, Ignan, Infernal, Nagaji, Orc, Samsaran, Sylvan, Tengu, Terran, Undercommon
SQ arcane gun, fighter training, heavy armor, hex (misfortune), hex arcana, hex magus, infernal mortification, knowledge of the lost, knowledge pool, mage bullets, pass for human, ranged spell combat, ranged spellstrike, ranged weapon bond, spiritual form
Combat Gear boots of escape, mirror of guarding reflections, noble's vigilant pillbox; Other Gear celestial plate armor (upgraded), +5 mithral buckler, +5 enhanced revolver, bag of holding i, belt of incredible dexterity +6, cloak of resistance +5, cracked dusty rose prism ioun stone, headband of vast intelligence +6, heavyload belt, necklace of adaptation, ring of arcane mastery, rod of abrupt hexes, magus starting spellbook, wizard starting spellbook, 26,150 gp, 1 cp
Special Abilities
Absolute Solitude (Sp) Once per day, you can cast imprisonment.
Arcane Gun (Su) Imbue two firearms with magic; cast spells thru the firearms.
Arcane Pool +4 (14/day) (Su) Infuse own power into a held weapon, granting enhancement bonus or selected item powers.
Arcane Strike As a swift action, add +1 damage, +1 per 5 caster levels and your weapons are treated as magic for the purpose of overcoming damage reduction.
Darkvision (60 feet) You can see in the dark (black and white only).
Deadly Aim -3/+6 Trade a penalty to ranged attacks for a bonus to ranged damage.
Deific Obedience Purify yourself daily to prove devotion to a deity and gain benefits.
Dimensional Agility May take any additional actions remaining after using dimension door or abundant step
Dimensional Assault May use dimension door or abundant step as part of a charge action
Dimensional Dervish During full-attack action, you may cast dimension door or use abundant step as a swift action
Distant Spellstrike (Su) Ranged spellstrike range increases to maximum range of weapon if greater.
Divination You must spend 2 slots to cast spells from the Divination school.
Enchantment You must spend 2 slots to cast spells from the Enchantment school.
Fighter Training (Ex) Add half your Magus level to your Fighter level for the purpose of feats.
Forgetfulness (Sp) 3/day, stnd action, alter creature's memory as modify memory; 2 uses for 1 hour, 3 uses for 1 day.
Gunsmithing You can use a gunsmithing kit to craft/repair firearms and ammo.
Heavy Armor (Ex) Heavy armor proficiency and no Arcane Failure chance in heavy armor.
Hex Arcana You can substitute Hexes for Magus Arcana.
Hex Magus (Su) You gain access to witch hexes.
Illusion You must spend 2 slots to cast spells from the Illusion school.
Improved Spell Combat (Ex) Use weapon in one hand at -2 & cast a spell with the other. Gain additional +2 circumstance bonus on concentration checks when using spell combat.
Infernal Mortification (Su) As a standard action, increase arcane pool by 1 pt per 2 Con dam (only time can heal).
Knowledge of the Lost (Sp) identify 3/day, locate object 2/day, or crushing despair 1/day
Knowledge Pool (Su) Spend Arcane Pool points to prepare a magus spell that is not in your spellbook for 1 day.
Mage Bullets (Su) Sacrifice a spell to grant an enhancement bonus or special ability to arcane gun.
Misfortune (2 rounds, DC 24) (Su) Foe in 30 ft must take the lower of 2d20 for rolls (Will neg).
Necromancy You must spend 2 slots to cast spells from the Necromancy school.
Pass for Human You can pass for human, and count as a humanoid (human) for all purposes.
Point-Blank Shot +1 to attack and damage rolls with ranged weapons at up to 30 feet.
Precise Shot You don't get -4 to hit when shooting or throwing into melee.
Ranged Spell Combat (Ex) Must use ranged weapon for spell combat.
Ranged Spellstrike (Su) As a full rd action, ranged spells can be combined with ranged attacks.
Ranged Weapon Bond (- custom / magic weapon -) (Ex) Must have bonded object to cast spells, doesn't interfere with somatic components.
Rapid Shot You get an extra attack with ranged weapons. Each attack is at -2.
Reach Spellstrike (Su) Touch spells increase range to close with ranged spellstrike ability.
Slumber (13 rounds, DC 24) (Su) Foe in 30 ft falls asleep for duration, or until damaged or roused by ally (Will neg).
Spell Cartridges With Arcane Strike, you may fire force bullets dealing 1d4 force dam per 5 CL.
Spellstrike (Su) Deliver touch spells as part of a melee attack.
Spiritual Form (Dexterity, Wings, 10 minutes/day) As a standard action, gain telepathy, stat boost, and ability of choice.```

**Comment by baileymh** [comment]
Hanhula, as prestige classes aren't very well supported by the current system, and these are the first pack of them that I am aware of, it's likely sbc hasn't included support for them yet, which is understandable. 

However, it would be great for the feats, abilities, and all the items that were in the latest pf-content update to be usable on import.

**Comment by Hanhula** [comment]
Far as I'm aware - and Primer's welcome to correct - the custom compendia's meant to just pull in any custom class!

**Comment by Lavaeolous** [comment]
> Far as I'm aware - and Primer's welcome to correct - the custom compendia's meant to just pull in any custom class!

Yeah, that is the intention, but it seems it's not implemented all too well :)

I've found multiple issues with that, and one is that prestige classes in specific have an override right now. I'll take a look how i can fix that so this just is used when no entry could be found anywhere.

**Comment by Lavaeolous** [comment]
https://user-images.githubusercontent.com/14833806/115989628-93169780-a5bf-11eb-87d2-e5a2be20de9a.mp4

Prestige Classes can now be parsed from custom compendia in v3.1.1, which should be online tomorrow or so.
Caveats are, that SBC **does not** support class associations, so if the feature is not listed in the statblock, it will not get parsed.

If the prestige class can't be found in any compendia it will generate a placeholder as before.

I would be happy if you could try this again when its online.

**Comment by Lavaeolous** [comment]
v3.1.1 is now online

**Comment by Hanhula** [comment]
Now this is interesting. 
Using these as imports:
```world.hans-magic-items, world.hans-class-abilities, world.hans-classes, world.hans-mythic-abilities, world.hans-feats, world.hans-common-buffs, world.hans-traits, world.hans-spells, pf-content.pf-feats,  pf-content.pf-traits, pf-content.pf-racial-traits, pf-content.pf-artifacts, pf-content.pf-magicitems, pf-content.pf-wondrous, pf-content.pf-35-content, pf-content.pf-goods-services, pf-content.pf-items, pf-content.pf-special-qualities, pf-content.mythic-adventures, pf-content.horror-adventures, pf1e-archetypes.pf-archetypes, pf1e-archetypes.pf-class-abilities, pf1e-archetypes.pf-arch-features, pf1e-archetypes.pf-prestige-classes, pf1e-archetypes.pf-prestige-features```

My above statblock doesn't import Evangelist properly like yours does; it generates a placeholder, but one with an icon.

![See here?](https://i.imgur.com/MlkXKUJ.png)

This was consistent when I tested a few others that had prestige classes as well. Looks like archetypes are being handled properly, but not prestiges.

**Comment by Lavaeolous** [comment]
I can reproduce that and have created a specific issue for that. Thanks for testing again!

**Comment by Lavaeolous** [comment]
Should be fixed in 3.1.2, which is up any minute now. Please feel free to test again.

**Comment by Hanhula** [comment]
> Should be fixed in 3.1.2, which is up any minute now. Please feel free to test again.

Ah, you're gonna sigh at me. I'm not seeing a fix for #386, unfortunately -- the statblock I posted earlier still fails to grab Evangelist, and her feats don't correctly import as those in pf-content. I tested with all compendia selected and with my world-specific compendia removed.

Also just checked with *only* pf1e-archetypes.pf-prestige-classes - it works then! Compare: https://i.imgur.com/QVyNWwf.png However: adding pf-content.pf-feats doesn't *break* the import, but it also doesn't pull anything from the second compendium.

**Comment by Lavaeolous** [comment]
See separate issues: For the functionality i simply missed to remove extra spaces in the input compendia names. It should work in v3.1.3 now.

But, the conversion gets incredibly slow when using all compendia of pf1e-content and pf1e-archetypes

**Comment by Lavaeolous** [comment]
Could you post a statblock which i can use for testing and the compendium you are using?

**Comment by Hanhula** [comment]
> Could you post a statblock which i can use for testing and the compendium you are using?

Sure!

```Tesutra
Female aasimar cleric 13/(Mythic) Hierophant 2
LN Medium outsider (native)
Init +5; Senses darkvision 60 ft.; Perception +24
Defense
AC 27, touch 11, flat-footed 26 (+12 armor, +1 Dex, +4 shield)
hp 151 (13d8+47)
Fort +15, Ref +12, Will +22; +2 vs. evil
Defensive Abilities hard to kill; Resist acid 5, cold 20, electricity 5
Offense
Speed 30 ft. (20 ft. in armor), fly 20 ft. (poor)
Melee +3 ghost touch morningstar +12/+7 (1d8+3)
Special Attacks channel positive energy 4/day (DC 17, 7d6), divine surge (inspired spell), inspired spell[MA], mythic power (7/day, surge +1d6)
Spell-Like Abilities (CL 13th; concentration +14)
   1/day—daylight
Domain Spell-Like Abilities (CL 13th; concentration +22)
   12/day—icicle (1d6+6 cold), rebuke death (1d4+6)
Cleric Spells Prepared (CL 13th; concentration +22)
   7th—destruction (DC 26), elemental body IV (water only)[D], ethereal jaunt
   6th—animate objects, blade barrier (DC 25), cone of cold[D,M] (DC 25), heal
   5th—break enchantment, breath of life[D] (DC 24), flame strike (DC 24), raise dead, slay living (DC 24), true seeing
   4th—air walk, control water[D], cure critical wounds, dimensional anchor, divine power, holy smite (DC 23), mythic severance[MA] (DC 23)
   3rd—bestow curse (DC 22), cure serious wounds[D], daylight, dispel magic, invisibility purge, prayer[M], prayer[M]
   2nd—cure moderate wounds[D], make whole, resist energy, shield other, silence (DC 21), sound burst (DC 21), status (DC 21)
   1st—bless, cure light wounds, endure elements, obscuring mist[D], protection from evil, sanctuary (DC 20), shield of faith, stone shield
   0 (at will)—create water, detect magic, guidance, mending
   D Domain spell; Domains Healing, Water
   M mythic spell
Statistics
Str 11, Dex 16, Con 14, Int 15, Wis 29, Cha 12
Base Atk +9; CMB +9; CMD 22
Feats Angel Wings, Angelic Blood, Channel Smite, Channel Smite (Mythic), Combat Casting, Heavy Armor Proficiency, Maximize Spell, Spell Penetration
Traits fate's favored
Skills Acrobatics -3 (-7 to jump), Appraise +6, Diplomacy +11, Fly -2, Heal +22 (+26 dealing with humanoid pregnancy or birth), Knowledge (history) +8, Knowledge (nobility) +7, Knowledge (planes) +10, Knowledge (religion) +8, Perception +24, Sense Motive +17, Spellcraft +8; Racial Modifiers +2 Diplomacy, +2 Perception
Languages Abyssal, Celestial, Common, Infernal
SQ amazing initiative, healer's blessing, mythic spellcasting, relentless healing
Combat Gear potion of cure light wounds, alchemist's kindness (2), antiplague (2), antitoxin (2), bloodblock (2), healer's kit, smelling salts (2), soothe syrup (3); Other Gear celestial plate armor, celestial shield, +3 ghost touch morningstar, bag of holding i, cloak of resistance +5, headband of inspired wisdom +6, backpack, bedroll, belt pouch, belt pouch, bottle of strong brandy (1.5 lb), candle (10), doctor's mask, flint and steel, hemp rope (50 ft.), holy text (Pharasma), mess kit, midwife's kit, pot, soap, spell component pouch, torch (10), trail rations (5), waterskin, wooden holy symbol, 1,846 gp
Special Abilities
Amazing Initiative (1/round) (Ex) As a free action, use 1 power to gain an extra standard action (can't be used to cast a spell).
Angelic Blood +2 saves vs. evil effects, to stabilize while dying, and 1 damage to evil or undead if bleeding.
Channel Smite [Mythic] Bonus to att when use Channel Smite, if miss use 1 power to release it as a normal channel.
Cleric Channel Positive Energy 7d6 (4/day, DC 17) (Su) Positive energy heals the living and harms the undead; negative has the reverse effect.
Cleric Domain (Healing) Granted Powers: Your touch staves off pain and death, and your healing magic is particularly vital and potent.
Cleric Domain (Water) Granted Powers: You can manipulate water and mist and ice, conjure creatures of water, and resist cold.
Combat Casting +4 to Concentration checks to cast while on the defensive.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Acid (5) You have the specified Energy Resistance against Acid attacks.
Energy Resistance, Cold (20) You have the specified Energy Resistance against Cold attacks.
Energy Resistance, Electricity (5) You have the specified Energy Resistance against Electricity attacks.
Fly (20 feet, Poor) You can fly!
Hard to Kill (Ex) Automatically stabilize when dying, and only die at neg Con x 2.
Healer's Blessing (Su) Your cure spells are empowered for free.
Icicle 1d6+6 cold (12/day) (Sp) As a standard action, ranged touch attack deals cold dam to foe in 30 ft.
Inspired Spell (Su) Use 1 power, cast one divine spell from your class spell list at +2 CL, it doesn't need to be known/memorized.
Maximize Spell All variable effects of a spell are maximized. +3 Levels.
Rebuke Death (12/day) (Sp) As a standard action, touch heals 1d4+6 dam to negative HP target.
Relentless Healing (Su) Spend 1 power to apply a healing spell or ability to a creature that has died within 1 round.
Surge (1d6) (Su) Use 1 power to increase any d20 roll by the listed amount.```

Mythic parsing is understandably broken in this one, but feats will break whether or not she's listed as being mythic.  Using:
`world.hans-magic-items, world.hans-class-abilities, world.hans-classes, world.hans-mythic-abilities, world.hans-feats, world.hans-common-buffs, world.hans-traits, world.hans-spells, pf-content.pf-feats, pf-content.pf-traits, pf-content.pf-racial-traits, pf-content.pf-artifacts, pf-content.pf-magicitems, pf-content.pf-wondrous, pf-content.pf-35-content, pf-content.pf-goods-services, pf-content.pf-items, pf-content.pf-special-qualities, pf-content.mythic-adventures, pf-content.horror-adventures, pf1e-archetypes.pf-archetypes, pf1e-archetypes.pf-class-abilities, pf1e-archetypes.pf-arch-features, pf1e-archetypes.pf-prestige-classes, pf1e-archetypes.pf-prestige-features`

**Comment by Lavaeolous** [comment]
Ah yes, thanks for the statblock. I found an error which prevented feats to be found (or more specifically to be searched for) in custom compendia. This should be fixed in 3.1.6, which i've uploaded a moment ago.

Feel free to test again!
